import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "../../node_modules/next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.classNameName}>
        <nav>
          <ul className="flex m-4 justify-end">
            <li className="mr-6">
              <Link href="/">
                <p className="text-red-700 hover:text-red-900" >Home</p>
              </Link>
            </li>
            <li className="mr-6">
              <Link href="/First-Page">
                <p className="text-red-700 hover:text-red-900" >First Page</p>
              </Link>
            </li>
            <li className="mr-6">
              <Link href="/">
                <p className="text-red-700 hover:text-red-900" >About</p>
              </Link>
            </li>

          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
